export { default as apiClient } from './client'
export { authAPI } from './auth'
export { examsAPI } from './exams'
export { gradesAPI } from './grades'
export { rubricsAPI } from './rubrics'
export { submissionsAPI } from './submissions'
